@2、createTables.sql
@3、createViews.sql
@4、createProcedures.sql
@5、initModuleAndRole.sql
@6、initDataDictionary.sql
@7、initOthers.sql
@8、createSequences.sql
@9、createTriggers.sql
@10、createJobs.sql
exit