idAndIpPort:
   corePoolSize: 100
   maximumPoolSize: 120
   keepAliveTime: 5
   wattingCount: 0
dataSynchronization:
   corePoolSize: 100
   maximumPoolSize: 120
   keepAliveTime: 5
   wattingCount: 0