oem:                    #oem配置 名称、简介、背景、图标、样式等
   #feizhou
   title: 智能化监控系统   #软件名称
   profile: 《智能化监控系统》 主要针对泵设备和管设备系列产品，通过驱动配置，实现采集、控制与报警等功能。模块包括实时监控、历史查询、生产报表、故障查询、设备日志、系统日志、计算维护、驱动配置、权限管理（组织用户、角色管理）、设备管理（设备信息、辅件设备、短信设备）和系统配置（模块配置、字典配置）等功能。
   copy: ""               #技术支持
   linkaddress: ""
   linkshow: ""
   favicon: "./oem/feizhou/images/logo/logo.png"      #网页图标
   logo: "./oem/feizhou/images/logo/logo.png"            #软件logo
   loginBackgroundImage: "./oem/feizhou/images/login/login.jpg"  #登录界面背景图片
   loginCSS: "./oem/feizhou/styles/login.css"            #登录界面CSS
   bannerCSS: "./oem/feizhou/styles/banner.css"          #主界面banner CSS
   helpButtonIcon: "./oem/feizhou/images/help.svg"            #帮助按钮图标
   exitButtonIcon: "./oem/feizhou/images/exit.svg"            #退出按钮图标
   zoomInButtonIcon: "./oem/feizhou/images/zoomin.svg"        #放大按钮图标
   zoomoutButtonIcon: "./oem/feizhou/images/zooout.svg"       #缩小按钮图标
   staticResourceTimestamp: 20240819090000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
   helpDocument: "./oem/feizhou/readme/help.html"             #帮助文档
   helpDocumentTimestamp: 20241118100000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
report:                                   #报表配置
   template: oem/feizhou/reportTemplate/reportTemplate.json   #报表模板
   offsetHour: 0                          #偏移小时 数值范围：0~12
   interval: 1                            #间隔 单位：小时 数值范围：1~12
   delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
email:                #邮件发送账号配置
   snedAccount:
      account: shfzby@126.com          #邮箱账号
      password: WYWHZENVGKLPZWIR       #邮箱授权码或独立密码
      smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
      smtpPort: 465                    #邮箱SMTP端口，以实际为准
others:
   deviceShowName: 设备名称
   cache: false
   language: zh_CN
   pageSize: 100
   syncOrAsync: false
   expandedAll: true
   defaultComboxSize: 10000
   defaultGraghSize: 30            #图形平铺每页图形数量
   vacuateThreshold: 300           #历史曲线、图形抽稀阈值
   productionUnit: stere           #产量单位 stere-立方米 ton-吨
   resourceMonitoringSaveData: 50000 #资源检测保存历史记录数
   resourceMonitoringVacuateThreshold: 5000           #资源监测曲线抽稀阈值
   iot: true                      #是否为物联网模式
   scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
   module: ""                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
   showVideo: false                     #是否含视频
   showLogo: true                  #是否显示图标
   printLog: false                  #是否打印日志
   exportAdInitData: false         #是否可导出ad初始化数据
   rangeLimit: 100                 #在线区间和运行区间，数组最大长度，超过将覆盖，0-无上限
   exportLimit: 10000              #导出excel数据上限
   simulateAcqEnable: false         #是否发送模拟数据，用于演示
   sendCycle: 600                  #模拟数据发送周期，单位：秒
   timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
   otherStaticResourceTimestamp: 20241101100000  #其他静态资源时间戳，修改此项重新加载资源