oem:                    #oem配置 名称、简介、背景、图标、样式等
   title: 油气生产智能监控系统 V9.3   #软件名称
   profile: 《油气生产智能监控系统 V9.3》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
   copy: ""               #技术支持
   linkaddress: ""
   linkshow: ""
   favicon: "./oem/zhuchuang/images/logo/favicon.ico"
   logo: "./oem/zhuchuang/images/logo/logo.png"
   loginBackgroundImage: "./oem/zhuchuang/images/login/login.jpg"
   loginCSS: "./oem/zhuchuang/styles/login.css"
   bannerCSS: "./oem/zhuchuang/styles/banner.css"
   helpButtonIcon: "./oem/zhuchuang/images/help.svg"            #帮助按钮图标
   exitButtonIcon: "./oem/zhuchuang/images/exit.svg"            #退出按钮图标
   zoomInButtonIcon: "./oem/zhuchuang/images/zoomin.svg"        #放大按钮图标
   zoomoutButtonIcon: "./oem/zhuchuang/images/zooout.svg"       #缩小按钮图标
   staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
   helpDocument: "./oem/zhuchuang/readme/help.html"             #帮助文档
   helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
report:                                   #报表配置
   template: oem/zhuchuang/reportTemplate/reportTemplate.json   #报表模板
   offsetHour: 0                          #偏移小时 数值范围：0~12
   interval: 1                            #间隔 单位：小时 数值范围：1~12
   delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
email:                #邮件发送账号配置
   snedAccount:
      account: 123456@126.com          #邮箱账号
      password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
      smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
      smtpPort: 465                    #邮箱SMTP端口，以实际为准
others:
   deviceShowName: 设备名称
   cache: false
   language: zh_CN
   pageSize: 100
   syncOrAsync: false
   expandedAll: true
   defaultComboxSize: 10000
   defaultGraghSize: 30            #图形平铺每页图形数量
   vacuateThreshold: 300           #历史曲线、图形抽稀阈值
   productionUnit: stere           #产量单位 stere-立方米 ton-吨
   resourceMonitoringSaveData: 50000 #资源检测保存历史记录数
   resourceMonitoringVacuateThreshold: 5000           #资源监测曲线抽稀阈值
   iot: true                      #是否为物联网模式
   scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
   module: all                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
   showVideo: true                     #是否含视频
   showLogo: true                  #是否显示图标
   printLog: true                  #是否打印日志
   exportAdInitData: false         #是否可导出ad初始化数据
   rangeLimit: 100                 #在线区间和运行区间，数组最大长度，超过将覆盖，0-无上限
   exportLimit: 10000              #导出excel数据上限
   simulateAcqEnable: false         #是否发送模拟数据，用于演示
   sendCycle: 600                  #模拟数据发送周期，单位：秒
   timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
   otherStaticResourceTimestamp: 20241101100000  #其他静态资源时间戳，修改此项重新加载资源