/*==============================================================*/
/* 初始化组织数据                                                 */
/*==============================================================*/
insert into TBL_ORG (ORG_ID, ORG_CODE, ORG_NAME_ZH_CN, ORG_NAME_EN, ORG_NAME_RU, ORG_MEMO, ORG_PARENT, ORG_SEQ)
values (2, '1000', '油田公司', 'Oilfield Company', '油田公司', null, 1, 1);

insert into TBL_ORG ( ORG_CODE, ORG_NAME_ZH_CN,ORG_NAME_EN,ORG_NAME_RU, ORG_MEMO, ORG_PARENT, ORG_SEQ)
select '100001','采油一厂','First Plant','采油一厂','',t2.org_id, 11 from TBL_ORG t2 where t2.org_code='1000';

insert into TBL_ORG ( ORG_CODE, ORG_NAME_ZH_CN,ORG_NAME_EN,ORG_NAME_RU, ORG_MEMO, ORG_PARENT, ORG_SEQ)
select '100002','采油二厂','Second Plant','采油二厂','',t2.org_id, 12 from TBL_ORG t2 where t2.org_code='1000';


/*==============================================================*/
/* 初始化设备数据                                              */
/*==============================================================*/
insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP01', 1, 1, 'TCP Client', '1010001', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 'ezopen://open.ys7.com/G39444019/1.live', null, 1, null, null, '{"FluidPVT":{"CrudeOilDensity":0.87,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.63,"SaturationPressure":9.7},"Reservoir":{"Depth":1657.0,"Temperature":69.0},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":1069.0,"OutsideDiameter":0.022,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"H","PumpGrade":2,"PlungerLength":1.5,"PumpBoreDiameter":0.057},"CasingString":{"EveryCasing":[{"InsideDiameter":0.139}]},"Production":{"WaterCut":97.02,"WeightWaterCut":97.4,"ProductionGasOilRatio":75.0,"TubingPressure":0.64,"CasingPressure":0.7,"WellHeadTemperature":26.0,"ProducingfluidLevel":190.0,"PumpSettingDepth":1113.72},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('29-03-2024 10:58:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 1.40, '{"EveryBalance":[{"Position":"0.5","Weight":"2.646"},{"Position":"0.5","Weight":"2.646"},{"Position":"0.5","Weight":"2.646"},{"Position":"0.5","Weight":"2.646"}]}', 1, 1, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP02', 1, 0, 'TCP Client', '1010002', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.0,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":0.0},"Reservoir":{"Depth":946.5,"Temperature":48.1},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":840.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":2.5,"PumpBoreDiameter":0.038},"CasingString":{"EveryCasing":[{"InsideDiameter":0.121}]},"Production":{"WaterCut":100.0,"WeightWaterCut":100.0,"ProductionGasOilRatio":1.0,"TubingPressure":0.7,"CasingPressure":0.55,"WellHeadTemperature":26.0,"ProducingfluidLevel":792.9,"PumpSettingDepth":855.28},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('24-05-2024 14:13:27', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"}]}', 1, 2, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP03', 1, 1, 'TCP Client', '1010003', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1134.6,"Temperature":56.6},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":1038.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":1.6,"PumpBoreDiameter":0.032},"CasingString":{"EveryCasing":[{"InsideDiameter":0.121}]},"Production":{"WaterCut":39.84,"WeightWaterCut":43.5,"ProductionGasOilRatio":20.2,"TubingPressure":0.34,"CasingPressure":0.21,"WellHeadTemperature":26.0,"ProducingfluidLevel":1033.0,"PumpSettingDepth":1053.2},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('24-05-2024 14:13:27', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"}]}', 1, 3, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP04', 1, 1, 'TCP Client', '1010004', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1052.9,"Temperature":52.9},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":945.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":2.5,"PumpBoreDiameter":0.038},"CasingString":{"EveryCasing":[{"InsideDiameter":0.124}]},"Production":{"WaterCut":79.01,"WeightWaterCut":81.4,"ProductionGasOilRatio":20.2,"TubingPressure":0.37,"CasingPressure":0.32,"WellHeadTemperature":26.0,"ProducingfluidLevel":923.8,"PumpSettingDepth":959.38},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('30-09-2024 15:06:38', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.9","Weight":"7.74"}]}', 1, 4, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP05', 1, 1, 'TCP Client', '1010005', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1202.5,"Temperature":59.6},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":1150.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":1.6,"PumpBoreDiameter":0.032},"CasingString":{"EveryCasing":[{"InsideDiameter":0.121}]},"Production":{"WaterCut":46.73,"WeightWaterCut":50.5,"ProductionGasOilRatio":20.2,"TubingPressure":0.31,"CasingPressure":0.2,"WellHeadTemperature":26.0,"ProducingfluidLevel":1152.0,"PumpSettingDepth":1161.75},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('29-05-2024 16:56:18', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.1","Weight":"7.75"}]}', 1, 5, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP06', 1, 1, 'TCP Client', '1010006', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1035.7,"Temperature":52.1},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":929.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":1.6,"PumpBoreDiameter":0.032},"CasingString":{"EveryCasing":[{"InsideDiameter":0.121}]},"Production":{"WaterCut":42.77,"WeightWaterCut":46.5,"ProductionGasOilRatio":20.2,"TubingPressure":0.32,"CasingPressure":0.21,"WellHeadTemperature":26.0,"ProducingfluidLevel":885.1,"PumpSettingDepth":940.39},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('29-05-2024 16:42:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":7.71},{"Position":"0.6","Weight":7.71},{"Position":"0.6","Weight":7.71},{"Position":"0.12","Weight":7.71}]}', 1, 6, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP07', 1, 1, 'TCP Client', '1010007', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1035.7,"Temperature":52.1},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":929.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":1.6,"PumpBoreDiameter":0.032},"CasingString":{"EveryCasing":[{"InsideDiameter":0.121}]},"Production":{"WaterCut":42.77,"WeightWaterCut":46.5,"ProductionGasOilRatio":20.2,"TubingPressure":0.32,"CasingPressure":0.21,"WellHeadTemperature":26.0,"ProducingfluidLevel":885.1,"PumpSettingDepth":940.39},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('29-05-2024 16:43:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"}]}', 1, 7, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP08', 1, 1, 'TCP Client', '1010008', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1012.4,"Temperature":51.1},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":931.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":2.5,"PumpBoreDiameter":0.038},"CasingString":{"EveryCasing":[{"InsideDiameter":0.121}]},"Production":{"WaterCut":52.36,"WeightWaterCut":56.1,"ProductionGasOilRatio":20.2,"TubingPressure":0.31,"CasingPressure":0.62,"WellHeadTemperature":26.0,"ProducingfluidLevel":900.4,"PumpSettingDepth":942.59},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('29-05-2024 16:44:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"}]}', 1, 8, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP09', 1, 1, 'TCP Client', '1010009', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1093.7,"Temperature":54.7},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":998.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":2.5,"PumpBoreDiameter":0.038},"CasingString":{"EveryCasing":[{"InsideDiameter":0.124}]},"Production":{"WaterCut":41.6,"WeightWaterCut":45.3,"ProductionGasOilRatio":20.2,"TubingPressure":0.31,"CasingPressure":0.75,"WellHeadTemperature":26.0,"ProducingfluidLevel":969.3,"PumpSettingDepth":1015.58},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('29-05-2024 16:45:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"}]}', 1, 9, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'SRP10', 1, 1, 'TCP Client', '1010010', null, '01', null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.86,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.6,"SaturationPressure":3.68},"Reservoir":{"Depth":1093.7,"Temperature":54.7},"RodString":{"EveryRod":[{"Type":1,"Grade":"HY","Length":998.0,"OutsideDiameter":0.019,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelType":"L","PumpGrade":1,"PlungerLength":2.5,"PumpBoreDiameter":0.038},"CasingString":{"EveryCasing":[{"InsideDiameter":0.124}]},"Production":{"WaterCut":41.6,"WeightWaterCut":45.3,"ProductionGasOilRatio":20.2,"TubingPressure":0.31,"CasingPressure":0.75,"WellHeadTemperature":26.0,"ProducingfluidLevel":969.3,"PumpSettingDepth":1015.58},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0,"LevelCorrectValue":0.0}}', to_date('03-06-2024 21:08:34', 'dd-mm-yyyy hh24:mi:ss'), 0, 2.50, '{"EveryBalance":[{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"},{"Position":"0.6","Weight":"7.71"}]}', 1, 10, 1 from TBL_ORG t2 where t2.org_code='100001';

insert into tbl_device (ORGID, DEVICENAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, IPPORT, SLAVE, PEAKDELAY, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, VIDEOURL1, VIDEOURL2, VIDEOKEYID1, VIDEOKEYID2, VIDEOACCESSTOKEN, PRODUCTIONDATA, PRODUCTIONDATAUPDATETIME, PUMPINGMODELID, STROKE, BALANCEINFO, STATUS, SORTNUM, CALCULATETYPE) select t2.org_id, 'PCP01', 2, 1, 'TCP Client', '2010001', null, '01', 5, 'instance2', null, 'displayinstance2', 'reportinstance2', null, null, null, null, null, '{"FluidPVT":{"CrudeOilDensity":0.87,"WaterDensity":1.0,"NaturalGasRelativeDensity":0.7,"SaturationPressure":9.6},"Reservoir":{"Depth":1350.15,"Temperature":66.15},"RodString":{"EveryRod":[{"Type":1,"Grade":"D","Length":246.0,"OutsideDiameter":0.022,"InsideDiameter":0.0},{"Type":1,"Grade":"D","Length":411.0,"OutsideDiameter":0.011,"InsideDiameter":0.0}]},"TubingString":{"EveryTubing":[{"OutsideDiameter":0.0,"InsideDiameter":0.062}]},"Pump":{"BarrelLength":10.15,"BarrelSeries":20,"RotorDiameter":0.059,"QPR":5.0E-4},"CasingString":{"EveryCasing":[{"InsideDiameter":0.127}]},"Production":{"WaterCut":80.7,"WeightWaterCut":82.78,"ProductionGasOilRatio":40.0,"TubingPressure":0.7,"CasingPressure":0.6,"WellHeadTemperature":26.0,"ProducingfluidLevel":645.25,"PumpSettingDepth":674.35},"ManualIntervention":{"Code":0,"NetGrossRatio":1.0,"NetGrossValue":0.0}}', to_date('14-05-2024 10:23:07', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, 1, 9999, 2 from TBL_ORG t2 where t2.org_code='100001';
commit;

exit;