/*==============================================================*/
/* 初始化设备数据                                              */
/*==============================================================*/
insert into TBL_RPCDEVICE (ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (1, 'test_01', 101, 0, 'TCP Client', '5d468f332f2a81d7', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 0);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (1, 1, 'SJB6-46', 101, 0, 'TCP Client', '00000001', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 1);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (2, 1, 'SJB5-14', 101, 0, 'TCP Client', '00000002', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 2);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (3, 1, 'SJB10-39', 101, 0, 'TCP Client', '00000003', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 3);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (4, 1, 'JZ-05', 101, 0, 'TCP Client', '00000004', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 4);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (5, 1, 'JZ-07', 101, 0, 'TCP Client', '00000005', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 5);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (6, 1, 'Y-Y04-1H', 101, 0, 'TCP Client', '00000006', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 6);

insert into TBL_RPCDEVICE (ID, ORGID, WELLNAME, DEVICETYPE, APPLICATIONSCENARIOS, TCPTYPE, SIGNINID, SLAVE, PEAKDELAY, IPPORT, INSTANCECODE, ALARMINSTANCECODE, DISPLAYINSTANCECODE, REPORTINSTANCECODE, STATUS, SORTNUM)
values (7, 1, 'Y-Y02-1H', 101, 0, 'TCP Client', '00000007', '01', null, null, 'instance1', 'alarminstance1', 'displayinstance1', 'reportinstance1', 1, 7);

commit;

exit;