Ext.define('AP.model.right.RightModuleInfoModel', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'mdId',
        type: 'int'
     }, {
        name: 'mdName',
        type: 'string'
     }, {
        name: 'mdShowname',
        type: 'string'
     }, {
        name: 'mdCode',
        type: 'string'
     }, {
        name: 'mdUrl',
        type: 'string'
     }, {
        name: 'mdControl',
        type: 'string'
     }, {
        name: 'mdIcon',
        type: 'string'
     }, {
        name: 'mdType',
        type: 'string'
     }, {
        name: 'mdSeq',
        type: 'string'
     }, {
        name: 'mdParentid',
        type: 'string'
     }],
    idProperty: 'threadid'
});