oem:                    #oem配置 名称、简介、背景、图标、样式等
   languageResourcePath: "oem/feizhou/locale"                #语言资源文件所在目录
   favicon: "./oem/feizhou/images/logo/logo.png"             #网页图标
   logo: "./oem/feizhou/images/logo/logo.png"                #软件图标
   loginBackgroundImage: "./oem/feizhou/images/login/login.jpg"  #登录界面背景图片
   loginCSS: "./oem/feizhou/styles"                           #css文件所在目录
   bannerCSS: "./oem/feizhou/styles"                          #css文件所在目录
   helpButtonIcon: "./oem/feizhou/images/help.svg"            #帮助按钮图标
   exitButtonIcon: "./oem/feizhou/images/exit.svg"            #退出按钮图标
   switchButtonIcon: "./oem/feizhou/images/switch.svg"        #语言切换按钮图标
   switchDisabledButtonIcon: "./oem/feizhou/images/switch_disabled.svg"        #语言切换不可用按钮图标
   zoomInButtonIcon: "./oem/feizhou/images/zoomin.svg"        #放大按钮图标
   zoomoutButtonIcon: "./oem/feizhou/images/zooout.svg"       #缩小按钮图标
   staticResourceTimestamp: 20250911172700  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
   helpDocument: "./oem/feizhou/readme"             #帮助文档所在目录
   helpDocumentTimestamp: 20250911172700  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
report:                                   #报表配置
   template: "oem/feizhou/reportTemplate/reportTemplate.json"   #报表模板
   offsetHour: 0                          #偏移小时 数值范围：0~12
   interval: 1                            #间隔 单位：小时 数值范围：1~12
   delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
databaseMaintenance:                      #数据库维护
   cycle: 1                               #删除历史数据执行周期，单位：天 ，0-不执行定期删除
   startTime: 01:10:00                    #删除历史数据执行时间，cycle非0时生效
   endTime: 01:50:00                      #删除历史数据执行结束时间，到时间未执行完毕，将强制停止
   singleDeleteTime: 10                   #单次删除时间，单位：天
   singleDeleteRecord: 1000               #单次删除记录数
   tableConfig:
      acqdata_hist:                       #采集数据历史表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      acqrawdata:                         #采集原始数据历史表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      alarminfo_hist:                     #报警数据历史表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      dailytotalcalculate_hist:           #日累计计算历史表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      dailycalculationdata:               #采集数据全天汇总表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      timingcalculationdata:              #采集数据定时汇总表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      srpacqdata_hist:                    #抽油机井计算数据历史表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      srpdailycalculationdata:            #抽油机井全天汇总计算数据表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      srptimingcalculationdata:           #抽油机井定时汇总计算数据表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      pcpacqdata_hist:                    #螺杆泵井计算数据历史表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      pcpdailycalculationdata:            #螺杆泵井全天汇总计算数据表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      pcptimingcalculationdata:           #螺杆泵井定时汇总计算数据表
         enabled: true                    #是否启用定时删除
         retentionTime: 180                #数据保留时间，单位：天
      acqdata_vacuate:                    #采集数据抽稀表
         enabled: true                    #是否启用定时删除
         retentionTime: 1200               #数据保留时间，单位：天
      srpacqdata_vacuate:                 #抽油机井计算数据抽稀表
         enabled: true                    #是否启用定时删除
         retentionTime: 1200               #数据保留时间，单位：天
      pcpacqdata_vacuate:                 #螺杆泵井计算数据抽稀表
         enabled: true                    #是否启用定时删除
         retentionTime: 1200               #数据保留时间，单位：天
email:                #邮件发送账号配置
   snedAccount:
      account: shfzby@126.com          #邮箱账号
      password: WYWHZENVGKLPZWIR       #邮箱授权码或独立密码
      smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
      smtpPort: 465                    #邮箱SMTP端口，以实际为准
moduleContent: 
   realTimeMonitoring: 
      FESDiagramResultData: false
   historyQuery: 
      FESDiagramResultData: false
   dataMaintaining: 
      FESDiagramResultData: false
      RPMResultData: false
   primaryDevice: 
      deviceExtendInformation: true
      additionalInformation: true
      auxiliaryDevice: true
      videoConfig: false
      calculateDataConfig: false
      FSDiagramConstruction: false
      systemParameterConfiguration: false
   dataDictionary: 
      calculateData: 0                 #0-时率计算 1-时率计算和功图计算 2-时率计算和转速计产 3-全部
      inputData: 0                     #0-无 1-功图计算录入数据 2-转速计产录入数据 3-全部
dataVacuate:
   vacuateRecord: 300              #进行抽稀时，保留的记录数
   saveInterval: 1                 #抽稀表数据保存间隔 单位：小时
   saveIntervalWaveRange: 5        #抽稀表数据保存间隔波动范围 单位：分钟
   vacuateThreshold: 50000         #抽稀阈值,总记录数据超过该值，将从抽稀表中查询数据
others:
   deviceShowName: 设备名称
   timeEfficiencyUnit: 2               #时率单位 1-小数 2-百分数
   cache: false
   loginLanguage: zh_CN                   #zh_CN en ru
   pageSize: 100
   syncOrAsync: false
   expandedAll: true
   defaultComboxSize: 10000
   defaultGraghSize: 30            #图形平铺每页图形数量
   productionUnit: stere           #产量单位 stere-立方米 ton-吨
   resourceMonitoringSaveData: 50000 #资源检测保存历史记录数
   resourceMonitoringVacuateThreshold: 5000           #资源监测曲线抽稀阈值
   iot: true                      #是否为物联网模式
   scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
   module: ""                     #模块 ""-仅监测 srp-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
   showLogo: true                  #是否显示图标
   printLog: false                  #是否打印日志
   exportAdInitData: false         #是否可导出ad初始化数据
   saveAcqRawData: true            #是否保存采集原始数据
   rangeLimit: 100                 #在线区间和运行区间，数组最大长度，超过将覆盖，0-无上限
   exportLimit: 10000              #导出excel数据上限
   simulateAcqEnable: true         #是否发送模拟数据，用于演示
   sendCycle: 600                  #模拟数据发送周期，单位：秒
   timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
   otherStaticResourceTimestamp: 20250911172700  #其他静态资源时间戳，修改此项重新加载资源