ap:
   datasource:           #数据库配置,一般只需修改ip、数据库名称、用户名、密码
      driverUrl: jdbc:oracle:thin:@127.0.0.1:1521/orclpdb
      driver: oracle.jdbc.driver.OracleDriver
      dialect: org.hibernate.dialect.Oracle10gDialect
      user: ap
      password: ap123#
   redis:                #redis配置 一般只需配置addr和password
      addr: 127.0.0.1    #服务器IP
      port: 6379         #端口
      password: ap123#   #密码 无密码时设为空字符串""
      maxActive: 1024    #连接池可用连接实例的最大数目
      maxIdle: 200       #连接池中的最大空闲连接
      maxWait: 10000     #连接池最大阻塞等待时间（毫秒）,负值表示没有限制
      timeOut: 10000     #连接超时时间（毫秒）
   oem:                  #oem配置 名称、简介、背景、图标、样式等
      title: 煤层气生产智能监控系统 V8.7   #软件名称
      #profile: 《煤层气生产智能监控系统 V8.7》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      profile: 《煤层气生产智能监控系统 V8.7》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: "技术支持：天津黑潮科技有限公司"               #技术支持
      linkaddress: ""
      linkshow: ""
      #图片及样式
      #heichao
      favicon: "./images/logo/favicon_heichao.ico"      #网页图标
      logo: "./images/logo/logo_heichao.png"            #软件logo
      loginBackgroundImage: "./images/login/login.jpg"  #登录界面背景图片
      loginCSS: "./styles/login_heichao.css"            #登录界面CSS
      bannerCSS: "./styles/banner_heichao.css"          #主界面banner CSS
      #cnpc
      #favicon: "./images/logo/favicon_cnpc.ico"
      #logo: "./images/logo/logo_cnpc.png"
      #loginBackgroundImage: "./images/login/login.jpg"
      #loginCSS: "./styles/login_cnpc.css"
      #bannerCSS: "./styles/banner_cnpc.css"
      #cnooc
      #favicon: "./images/logo/favicon_cnooc.ico"
      #logo: "./images/logo/logo_cnooc.png"
      #loginBackgroundImage: "./images/login/login.jpg"
      #loginCSS: "./styles/login_cnooc.css"
      #bannerCSS: "./styles/banner_cnooc.css"
      #zhuchuang
      #favicon: "./images/logo/favicon_zhuchuang.ico"
      #logo: "./images/logo/logo_zhuchuang.png"
      #loginBackgroundImage: "./images/login/login.jpg"
      #loginCSS: "./styles/login_zhuchuang.css"
      #bannerCSS: "./styles/banner_zhuchuang.css"
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20230427161730  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20230714163030  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
   email:                #邮件发送账号配置
      snedAccount:
         account: 123456@126.com          #邮箱账号
         password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
         smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
         smtpPort: 465                    #邮箱SMTP端口，以实际为准
   threadPool: 
      initIdAndIpPort:
         corePoolSize: 100
         maximumPoolSize: 120
         keepAliveTime: 5
         wattingCount: 0
      dataSynchronization:
         corePoolSize: 100
         maximumPoolSize: 120
         keepAliveTime: 5
         wattingCount: 0
      calculateMaintaining:
         corePoolSize: 20
         maximumPoolSize: 25
         keepAliveTime: 5
         wattingCount: 0
      totalCalculateMaintaining:
         corePoolSize: 20
         maximumPoolSize: 25
         keepAliveTime: 5
         wattingCount: 0
      outerDatabaseSync:
         corePoolSize: 80
         maximumPoolSize: 100
         keepAliveTime: 5
         wattingCount: 0
   others:
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: false                       #物联网
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: all                     #模块 ""-仅监测 all-全部 rpc-抽油机井功图计算 pcp-螺杆泵井转速计算
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: true         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20230628160030  #其他静态资源时间戳，修改此项重新加载资源
ac:                                                    #AC程序配置
   probe:                                              #状态监测
      app: http://8.142.92.84:18100/api/probe/app                               #运行状态监测
      mem: http://8.142.92.84:18100/api/probe/mem                               #服务器内存监测
      disk: http://8.142.92.84:18100/api/probe/disk                             #服务器磁盘监测
      host: http://8.142.92.84:18100/api/probe/host                             #服务器主机监测
      cpu: http://8.142.92.84:18100/api/probe/cpu                               #服务器 CPU 监测
   FESDiagram: http://8.142.92.84:18100/api/calc/rpc/fesdiagram/pro             #功图计算
   RPM: http://8.142.92.84:18100/api/calc/pcp/rpm                               #螺杆泵转速计产
   communication: http://8.142.92.84:18100/api/calc/plugin/timeeff/comm         #通信时率计算
   run: http://8.142.92.84:18100/api/calc/plugin/timeeff/run                    #运行时率计算
   energy: http://8.142.92.84:18100/api/calc/plugin/energy                      #能耗计算
   totalCalculation: http://8.142.92.84:18100/api/analy/total/well              #全井汇总
ad:                                                          #AD程序配置 
   init:                                                     #初始化配置
      server:                                                #目标服务器初始化
         url: http://8.142.92.84:19200/api/init/server                                #初始化路径
         content:                                            #始化内容 数组，可配置多个
            idOnlineStatusPushURL: http://127.0.0.1:16100/ap/api/acq/id/online       #ID在线状态推送URL
            idAcqGroupDataPushURL: http://127.0.0.1:16100/ap/api/acq/id/group       #ID采集组数据推送URL
            ipPortOnlineStatusPushURL: http://127.0.0.1:16100/ap/api/acq/ipport/online       #IPPort在线状态推送URL
            ipPortAcqGroupDataPushURL: http://127.0.0.1:16100/ap/api/acq/ipport/group       #IPPort采集组数据推送URL
      protocol: http://8.142.92.84:19200/api/init/protocol                            #协议初始化
      instance: http://8.142.92.84:19200/api/init/instance                            #实例初始化
      id: http://8.142.92.84:19200/api/init/id                                        #id初始化 下位机为tcp client模式
      ipPort: http://8.142.92.84:19200/api/init/ipport                                #idport初始化 下位机为tcp server模式
      SMS: http://8.142.92.84:19200/api/init/sms                                      #短信设备初始化
   rw:                                                       #读写路径配置
      readAddr: http://8.142.92.84:19200/api/read/id/addr                             #读地址路径 下位机为tcp client模式时使用
      readAddr_ipPort: http://8.142.92.84:19200/api/read/ipport/addr                  #读地址路径 下位机为tcp server模式时使用
      writeAddr: http://8.142.92.84:19200/api/write/id/addr                           #写地址路径 下位机为tcp client模式时使用
      writeAddr_ipPort: http://8.142.92.84:19200/api/write/ipport/addr                #写地址路径 下位机为tcp server模式时使用
      writeSMS: http://8.142.92.84:19200/api/write/sms                                #发送短信路径
   probe:                                                    #状态监测
      init: http://8.142.92.84:19200/api/probe/init                                   #初始化状态监测
      app: http://8.142.92.84:19200/api/probe/app                                     #运行状态监测
      online: http://8.142.92.84:19200/api/probe/online                               #在线状态监测
      cpu: http://8.142.92.84:19200/api/probe/cpu                                     #服务器 CPU 监测
      mem: http://8.142.92.84:19200/api/probe/mem                                     #服务器内存监测
      disk: http://8.142.92.84:19200/api/probe/disk                                   #服务器磁盘监测
      host: http://8.142.92.84:19200/api/probe/host                                   #服务器主机监测
   rpc:                                                      #rpc协议配置
      readTopicReq: http://8.142.92.84:19200/api/ctrl/req                             #请求配置数据路径
      writeTopicModel: http://8.142.92.84:19200/api/ctrl/model                        #模型数据下行路径
      writeTopicConf: http://8.142.92.84:19200/api/ctrl/conf                          #配置数据下行路径
      writeTopicRtc: http://8.142.92.84:19200/api/ctrl/rtc                            #时钟下行路径
      writeTopicDog: http://8.142.92.84:19200/api/ctrl/dog                            #看门狗重启路径
      writeTopicStopRpc: http://8.142.92.84:19200/api/ctrl/stoprpc                    #停抽下行路径