ap:
   datasource:
      driverUrl: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      driver: oracle.jdbc.driver.OracleDriver
      dialect: org.hibernate.dialect.Oracle10gDialect
      user: ap
      password: ap123#
   oem:
      title: 油气生产智能监控系统 V8.2
      profile: 《油气生产智能监控系统 V8.2》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: ""
      linkaddress: http://www.cosogoil.com
      linkshow: ""
   email:
      snedAccount:
         account: shfzby@126.com
         password: CANDRMRCDLKHUKQX
         smtpHost: smtp.126.com
         smtpPort: 465
   others:
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 60
      productionUnit: stere #产量单位 stere-立方米 ton-吨
      pcpHidden: false
      showLogo: true
      printLog: true
      simulateAcqEnable: true
      sendCycle: 600
      timeDifference: 60
ac:
   probe:
      app: 
       - http://8.142.92.84:18100/api/probe/app
      mem: 
       - http://8.142.92.84:18100/api/probe/mem
      disk: 
       - http://8.142.92.84:18100/api/probe/disk
      host: 
       - http://8.142.92.84:18100/api/probe/host
      cpu: 
       - http://8.142.92.84:18100/api/probe/cpu
   FESDiagram: 
    - http://8.142.92.84:18100/api/calc/rpc/fesdiagram/pro
   ESDiagram:
      inversion:
         enable: false
         url:
          - http://8.142.92.84:18100/api/calc/rpc/esdiagram/inversion/motorauto
   pcpProduction: 
    - http://8.142.92.84:18100/api/calc/pcp/rpm
   communication: 
    - http://8.142.92.84:18100/api/calc/plugin/timeeff/comm
   run: 
    - http://8.142.92.84:18100/api/calc/plugin/timeeff/run
   energy: 
    - http://8.142.92.84:18100/api/calc/plugin/energy
   totalCalculation:
      well: 
       - http://8.142.92.84:18100/api/analy/total/well
   plugin: 
      wellboreTrajectory: 
       - http://8.142.92.84:18100/api/calc/plugin/2xyz
      fa2fs: 
       - http://8.142.92.84:18100/api/plugin/fa2fs
ad:
   server: http://8.142.92.84:19200/api/init/server
   protocol: http://8.142.92.84:19200/api/init/protocol
   instance: http://8.142.92.84:19200/api/init/instance
   id: http://8.142.92.84:19200/api/init/id
   ipPort: http://8.142.92.84:19200/api/init/ipport
   SMS: http://8.142.92.84:19200/api/init/sms
   readAddr: http://8.142.92.84:19200/api/read/id/addr
   readAddr_ipPort: http://8.142.92.84:19200/api/read/ipport/addr
   writeAddr: http://8.142.92.84:19200/api/write/id/addr
   writeAddr_ipPort: http://8.142.92.84:19200/api/write/ipport/addr
   writeSMS: http://8.142.92.84:19200/api/write/sms
   probe:
      init: http://8.142.92.84:19200/api/probe/init
      app: http://8.142.92.84:19200/api/probe/app
      cpu: http://8.142.92.84:19200/api/probe/cpu
      mem: http://8.142.92.84:19200/api/probe/mem
      disk: http://8.142.92.84:19200/api/probe/disk
      host: http://8.142.92.84:19200/api/probe/host
   rpc: 
      readTopicReq: http://8.142.92.84:19300/api/ctrl/req
      writeTopicModel: http://8.142.92.84:19300/api/ctrl/model
      writeTopicConf: http://8.142.92.84:19300/api/ctrl/conf
      writeTopicRtc: http://8.142.92.84:19300/api/ctrl/rtc
      writeTopicDog: http://8.142.92.84:19300/api/ctrl/dog
      writeTopicStopRpc: http://8.142.92.84:19300/api/ctrl/stoprpc