oem:                    #oem配置 名称、简介、背景、图标、样式等
   languageResourcePath: oem/cnooc/locale
   favicon: "./oem/cnooc/images/logo/favicon.ico"
   logo: "./oem/cnooc/images/logo/logo.png"
   loginBackgroundImage: "./oem/cnooc/images/login/login.jpg"
   loginCSS: "./oem/cnooc/styles/login.css"
   bannerCSS: "./oem/cnooc/styles/banner.css"
   helpButtonIcon: "./oem/cnooc/images/help.svg"            #帮助按钮图标
   exitButtonIcon: "./oem/cnooc/images/exit.svg"            #退出按钮图标
   switchButtonIcon: "./oem/cnooc/images/switch.svg"        #语言切换按钮图标
   switchDisabledButtonIcon: "./oem/cnooc/images/switch_disabled.svg"        #语言切换不可用按钮图标
   zoomInButtonIcon: "./oem/cnooc/images/zoomin.svg"        #放大按钮图标
   zoomoutButtonIcon: "./oem/cnooc/images/zooout.svg"       #缩小按钮图标
   staticResourceTimestamp: 20250414103000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
   helpDocument: "./oem/cnooc/readme"             #帮助文档所在目录
   helpDocumentTimestamp: 20250414103000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
report:                                   #报表配置
   template: oem/cnooc/reportTemplate/reportTemplate.json    #报表模板
   offsetHour: 0                          #偏移小时 数值范围：0~12
   interval: 1                            #间隔 单位：小时 数值范围：1~12
   delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
databaseMaintenance:                      #数据库维护
   cycle: 0                               #删除历史数据执行周期，单位：天 ，0-不执行定期删除
   startTime: 01:00:00                    #删除历史数据执行时间，cycle非0时生效
   retentionTime: 365                     #历史数据保留时间，单位：天， cycle非0时生效
   singleDeleteTime: 10                   #单次删除时间，单位：天
   tableConfig:
      acqdata_hist: true              #采集数据历史表
      acqrawdata: true                #采集原始数据历史表
      alarminfo_hist: true            #报警数据历史表
      dailytotalcalculate_hist: true  #日累计计算历史表
      dailycalculationdata: true      #采集数据全天汇总表
      timingcalculationdata: true     #采集数据定时汇总表
      srpacqdata_hist: true           #抽油机井计算数据历史表
      srpdailycalculationdata: true   #抽油机井全天汇总计算数据表
      srptimingcalculationdata: true  #抽油机井定时汇总计算数据表
      pcpacqdata_hist: true           #螺杆泵井计算数据历史表
      pcpdailycalculationdata: true   #螺杆泵井全天汇总计算数据表
      pcptimingcalculationdata: true  #螺杆泵井定时汇总计算数据表
email:                #邮件发送账号配置
   snedAccount:
      account: 123456@126.com          #邮箱账号
      password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
      smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
      smtpPort: 465                    #邮箱SMTP端口，以实际为准
moduleContent: 
   realTimeMonitoring: 
      FESDiagramResultData: true
   historyQuery: 
      FESDiagramResultData: true
   primaryDevice: 
      deviceExtendInformation: true
      additionalInformation: true
      auxiliaryDevice: true
      videoConfig: true
      calculateDataConfig: true
      FSDiagramConstruction: true
      systemParameterConfiguration: true
   dataDictionary: 
      calculateData: 3                 #0-时率计算 1-时率计算和功图计算 2-时率计算和转速计产 3-全部
      inputData: 3                     #0-无 1-功图计算录入数据 2-转速计产录入数据 3-全部
others:
   deviceShowName: 设备名称
   timeEfficiencyUnit: 1               #时率单位 1-小数 2-百分数
   cache: false
   loginLanguage: zh_CN                   #登录界面语言，目前支持中、英、俄文  zh_CN en ru
   pageSize: 100
   syncOrAsync: false
   expandedAll: true
   defaultComboxSize: 10000
   defaultGraghSize: 30            #图形平铺每页图形数量
   vacuateThreshold: 300           #历史曲线、图形抽稀阈值
   productionUnit: stere           #产量单位 stere-立方米 ton-吨
   resourceMonitoringSaveData: 50000 #资源检测保存历史记录数
   resourceMonitoringVacuateThreshold: 5000           #资源监测曲线抽稀阈值
   iot: true                      #是否为物联网模式
   scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
   module: all                     #模块 ""-仅监测 srp-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
   showLogo: true                  #是否显示图标
   printLog: true                  #是否打印日志
   exportAdInitData: true         #是否可导出ad初始化数据
   saveAcqRawData: true            #是否保存采集原始数据
   rangeLimit: 100                 #在线区间和运行区间，数组最大长度，超过将覆盖，0-无上限
   exportLimit: 10000              #导出excel数据上限
   simulateAcqEnable: false         #是否发送模拟数据，用于演示
   sendCycle: 600                  #模拟数据发送周期，单位：秒
   timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
   otherStaticResourceTimestamp: 20250414103000  #其他静态资源时间戳，修改此项重新加载资源