list:
  - oem:                    #oem配置 名称、简介、背景、图标、样式等
      #cnpc
      title: 油气生产智能监控系统 V9.1   #软件名称
      profile: 《油气生产智能监控系统 V9.1》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: ""               #技术支持
      linkaddress: ""
      linkshow: ""
      favicon: "./images/logo/favicon_cnpc.ico"
      logo: "./images/logo/logo_cnpc.png"
      loginBackgroundImage: "./images/login/login.jpg"
      loginCSS: "./styles/login_cnpc.css"
      bannerCSS: "./styles/banner_cnpc.css"
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
    report:                                   #报表配置
      offsetHour: 0                          #偏移小时 数值范围：0~12
      interval: 1                            #间隔 单位：小时 数值范围：1~12
      delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
    email:                #邮件发送账号配置
      snedAccount:
        account: 123456@126.com          #邮箱账号
        password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
        smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
        smtpPort: 465                    #邮箱SMTP端口，以实际为准
    others:
      deviceShowName: 设备名称
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: true                      #是否为物联网模式
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: all                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
      showVideo: true                     #是否含视频
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: false         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20240729092000  #其他静态资源时间戳，修改此项重新加载资源
  - oem:                    #oem配置 名称、简介、背景、图标、样式等
      #cnooc
      title: 油气生产智能监控系统 V9.1   #软件名称
      profile: 《油气生产智能监控系统 V9.1》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: ""               #技术支持
      linkaddress: ""
      linkshow: ""
      favicon: "./images/logo/favicon_cnooc.ico"
      logo: "./images/logo/logo_cnooc.png"
      loginBackgroundImage: "./images/login/login.jpg"
      loginCSS: "./styles/login_cnooc.css"
      bannerCSS: "./styles/banner_cnooc.css"
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
    report:                                   #报表配置
      offsetHour: 0                          #偏移小时 数值范围：0~12
      interval: 1                            #间隔 单位：小时 数值范围：1~12
      delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
    email:                #邮件发送账号配置
      snedAccount:
        account: 123456@126.com          #邮箱账号
        password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
        smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
        smtpPort: 465                    #邮箱SMTP端口，以实际为准
    others:
      deviceShowName: 设备名称
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: true                      #是否为物联网模式
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: all                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
      showVideo: true                     #是否含视频
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: false         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20240729092000  #其他静态资源时间戳，修改此项重新加载资源
  - oem:                    #oem配置 名称、简介、背景、图标、样式等
      #功图软件
      title: 油井工况诊断与产量计算软件 V9.1   #软件名称
      profile: 《油井工况诊断与产量计算软件 V9.1》通过对示功图数据及油井基础数据进行分析，实现油井故障诊断及单井产量计算。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: ""               #技术支持
      linkaddress: ""
      linkshow: ""
      favicon: "./images/logo/favicon_cnpc.ico"
      logo: "./images/logo/logo_cnpc.png"
      loginBackgroundImage: "./images/login/login.jpg"
      loginCSS: "./styles/login_cnpc.css"
      bannerCSS: "./styles/banner_cnpc.css"
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
    report:                                   #报表配置
      offsetHour: 0                          #偏移小时 数值范围：0~12
      interval: 1                            #间隔 单位：小时 数值范围：1~12
      delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
    email:                #邮件发送账号配置
      snedAccount:
        account: 123456@126.com          #邮箱账号
        password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
        smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
        smtpPort: 465                    #邮箱SMTP端口，以实际为准
    others:
      deviceShowName: 设备名称
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: true                      #是否为物联网模式
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: all                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
      showVideo: true                     #是否含视频
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: false         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20240729092000  #其他静态资源时间戳，修改此项重新加载资源
  - oem:                    #oem配置 名称、简介、背景、图标、样式等
      #heichao
      title: 煤层气生产智能监控系统 V9.1   #软件名称
      profile: 《煤层气生产智能监控系统 V9.1》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: "技术支持：天津黑潮科技有限公司"               #技术支持
      linkaddress: ""
      linkshow: ""
      favicon: "./images/logo/favicon_heichao.ico"      #网页图标
      logo: "./images/logo/logo_heichao.png"            #软件logo
      loginBackgroundImage: "./images/login/login.jpg"  #登录界面背景图片
      loginCSS: "./styles/login_heichao.css"            #登录界面CSS
      bannerCSS: "./styles/banner_heichao.css"          #主界面banner CSS
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
    report:                                   #报表配置
      offsetHour: 0                          #偏移小时 数值范围：0~12
      interval: 1                            #间隔 单位：小时 数值范围：1~12
      delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
    email:                #邮件发送账号配置
      snedAccount:
        account: 123456@126.com          #邮箱账号
        password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
        smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
        smtpPort: 465                    #邮箱SMTP端口，以实际为准
    others:
      deviceShowName: 设备名称
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: true                      #是否为物联网模式
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: all                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
      showVideo: true                     #是否含视频
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: false         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20240729092000  #其他静态资源时间戳，修改此项重新加载资源
  - oem:                    #oem配置 名称、简介、背景、图标、样式等
      #feizhou
      title: 智能化监控系统   #软件名称
      profile: 《智能化监控系统》 主要针对泵设备和管设备系列产品，通过驱动配置，实现采集、控制与报警等功能。模块包括实时监控、历史查询、生产报表、故障查询、设备日志、系统日志、计算维护、驱动配置、权限管理（组织用户、角色管理）、设备管理（设备信息、辅件设备、短信设备）和系统配置（模块配置、字典配置）等功能。
      copy: ""               #技术支持
      linkaddress: ""
      linkshow: ""
      favicon: "./images/logo/favicon_fzby.ico"      #网页图标
      logo: "./images/logo/logo_fzby.png"            #软件logo
      loginBackgroundImage: "./images/login/login.jpg"  #登录界面背景图片
      loginCSS: "./styles/login_fzby.css"            #登录界面CSS
      bannerCSS: "./styles/banner_fzby.css"          #主界面banner CSS
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
    report:                                   #报表配置
      offsetHour: 0                          #偏移小时 数值范围：0~12
      interval: 1                            #间隔 单位：小时 数值范围：1~12
      delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
    email:                #邮件发送账号配置
      snedAccount:
        account: 123456@126.com          #邮箱账号
        password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
        smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
        smtpPort: 465                    #邮箱SMTP端口，以实际为准
    others:
      deviceShowName: 设备名称
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: true                      #是否为物联网模式
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: ""                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
      showVideo: false                     #是否含视频
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: false         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20240729092000  #其他静态资源时间戳，修改此项重新加载资源
  - oem:                    #oem配置 名称、简介、背景、图标、样式等
      #zhuchuang
      title: 油气生产智能监控系统 V9.1   #软件名称
      profile: 《油气生产智能监控系统 V9.1》主要在采集、控制的基础上，侧重油井智能分析。模块主要包括实时监控、历史查询、生产报表、故障查询、日志查询、计算维护、驱动配置、权限管理、设备管理、系统配置等。系统应用大数据分析方法，对工况、产量、液面、平衡、能耗等生产关键指标进行统计分析，及时发现生产不正常井，挖掘生产潜力井，提升对目标区块和单井的管控能力。
      copy: ""               #技术支持
      linkaddress: ""
      linkshow: ""
      favicon: "./images/logo/favicon_zhuchuang.ico"
      logo: "./images/logo/logo_zhuchuang.png"
      loginBackgroundImage: "./images/login/login.jpg"
      loginCSS: "./styles/login_zhuchuang.css"
      bannerCSS: "./styles/banner_zhuchuang.css"
      helpButtonIcon: "./images/help.svg"             #帮助按钮图标
      exitButtonIcon: "./images/exit.svg"             #退出按钮图标
      staticResourceTimestamp: 20240729092000  #oem相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
      helpDocument: "./readme/ap_cbm/help.html"             #帮助文档
      helpDocumentTimestamp: 20240625183000  #帮助文档相关的静态资源时间戳，修改此项重新加载资源，无需清理浏览器缓存，即可使其他修改生效
    report:                                   #报表配置
      offsetHour: 0                          #偏移小时 数值范围：0~12
      interval: 1                            #间隔 单位：小时 数值范围：1~12
      delay: 5                               #跨天汇总延时，单位：分钟 数值范围：0~30
    email:                #邮件发送账号配置
      snedAccount:
        account: 123456@126.com          #邮箱账号
        password: CANDRMRCDLKHUKQX       #邮箱授权码或独立密码
        smtpHost: smtp.126.com           #邮箱服务器地址，不同服务器地址不同
        smtpPort: 465                    #邮箱SMTP端口，以实际为准
    others:
      deviceShowName: 设备名称
      cache: false
      language: zh_CN
      pageSize: 100
      syncOrAsync: false
      expandedAll: true
      defaultComboxSize: 10000
      defaultGraghSize: 30            #图形平铺每页图形数量
      vacuateThreshold: 300           #历史曲线、图形抽稀阈值
      productionUnit: stere           #产量单位 stere-立方米 ton-吨
      iot: true                      #是否为物联网模式
      scene: all                      #应用场景 all-全部 oil-油井 cbm-煤层气井
      module: all                     #模块 ""-仅监测 rpc-仅抽油机井功图计算 pcp-仅螺杆泵井转速计算 all-全部 
      showVideo: true                     #是否含视频
      showLogo: true                  #是否显示图标
      printLog: true                  #是否打印日志
      exportLimit: 10000              #导出数据上限
      simulateAcqEnable: false         #是否发送模拟数据，用于演示
      sendCycle: 600                  #模拟数据发送周期，单位：秒
      timeDifference: 60              #模拟数据井之间发送间隔，单位：秒
      otherStaticResourceTimestamp: 20240729092000  #其他静态资源时间戳，修改此项重新加载资源