Ext.define("AP.model.wellTrajectory.WellTrajectoryInfoModel", {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'jlbh',
        type: 'int'
     }, {
        name: 'jh',
        type: 'string'
     }, {
        name: 'jbh',
        type: 'int'
     }, {
        name: 'clsd',
        type: 'number'
     }, {
        name: 'czsd',
        type: 'number'
     }, {
        name: 'jxj',
        type: 'number'
     }, {
        name: 'fwj',
        type: 'number'
     }, {
        name: 'jsgj',
        type: 'string'
     }],
    idProperty: 'threadid'
})